#!/bin/bash

pkglist=(
adamraichu.font-viewer
adpyke.vscode-sql-formatter
akamud.vscode-theme-onedark
akamud.vscode-theme-onelight
aliariff.vscode-erb-beautify
astro-build.astro-vscode
bradlc.vscode-tailwindcss
CraigMaslowski.erb
cssho.vscode-svgviewer
DavidAnson.vscode-markdownlint
dbaeumer.vscode-eslint
DotJoshJohnson.xml
dracula-theme.theme-dracula
eamodio.gitlens
esbenp.prettier-vscode
file-icons.file-icons
george-alisson.html-preview-vscode
GitHub.copilot
GitHub.github-vscode-theme
github.vscode-github-actions
GitHub.vscode-pull-request-github
golang.go
jock.svg
LaurentTreguier.vscode-simple-icons
mechatroner.rainbow-csv
micnil.vscode-checkpoints
mikestead.dotenv
ms-azuretools.vscode-docker
ms-python.black-formatter
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter-keymap
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode.cpptools
ms-vscode.remote-explorer
naumovs.color-highlight
ninoseki.vscode-gem-lens
Prisma.prisma
rayhanw.erb-helpers
rebornix.ruby
redhat.java
redhat.vscode-commons
redhat.vscode-yaml
rokoroku.vscode-theme-darcula
rust-lang.rust-analyzer
samuelcolvin.jinjahtml
streetsidesoftware.code-spell-checker
svelte.svelte-vscode
tamasfe.even-better-toml
techer.open-in-browser
tomoki1207.pdf
unifiedjs.vscode-mdx
vadimcn.vscode-lldb
vayan.haml
VisualStudioExptTeam.intellicode-api-usage-examples
VisualStudioExptTeam.vscodeintellicode
vscjava.vscode-java-debug
vscjava.vscode-java-dependency
vscjava.vscode-java-pack
vscjava.vscode-java-test
vscjava.vscode-maven
vscode-icons-team.vscode-icons
whizkydee.material-palenight-theme
wingrunr21.vscode-ruby
wix.vscode-import-cost
xyc.vscode-mdx-preview
zh9528.file-size
zhuangtongfa.material-theme
)

for i in ${pkglist[@]}; do
  code --install-extension $i
done